ulti/frontend/models.py
from datetime import datetime

from flask import current_app as app

from .constants import *
from ..extensions import db
from ..utils import slugify, mongo_to_dict
from ..user import User

class Team(db.Document):
    admins = db.ListField(db.ReferenceField(User), default=[])
    name = db.StringField(unique=True)
    slug = db.StringField(unique=True)
    roster_url = db.StringField(unique=True)
    twitter = db.StringField(unique=True)
    fb_url = db.StringField(unique=True)
    email = db.StringField()
    logo = db.StringField()
    picture = db.StringField()
    #division = db.StringField(choices=DIVISIONS)
    brief_about = db.StringField(max_length=255)
    description = db.StringField()

    created_time = db.DateTimeField(default=datetime.utcnow(),
            required=True)
    last_update = db.DateTimeField(default=datetime.utcnow(),
            required=True)

    def clean(self):
        '''Clean Data!
           Runs before each save
        '''
        if not self.slug:
            self.slug = slugify(self.name)

        # Add last update timestamp
        self.last_update = datetime.utcnow()

    def to_dict(self):
        return mongo_to_dict(self)

ulti/user/models.py
from hashlib import md5

from flask.ext.security import login_required, RoleMixin, UserMixin

from ..extensions import db


class Role(db.Document, RoleMixin):
    name = db.StringField(max_length=80, unique=True)
    description = db.StringField(max_length=255)

class User(db.DynamicDocument, UserMixin):
    email = db.StringField(max_length=255)
    password = db.StringField(max_length=255)
    active = db.BooleanField(default=True)
    roles = db.ListField(db.ReferenceField(Role), default=[])
    last_login_at = db.DateTimeField()
    current_login_at = db.DateTimeField()
    last_login_ip = db.StringField()
    current_login_ip = db.StringField()
    login_count = db.IntField()

    def avatar(self, size):
        if self.email is None:
            self.email = ''
        return ('http://www.gravatar.com/avatar/'
                + md5(self.email).hexdigest() + '?d=mm&s=' + str(size))

    def get(self, key, no_attr=None):
        try:
            return self[key]
        except KeyError:
            return no_attr

ulti/admin/forms.py
from flask.ext.wtf import Form
from flask.ext.wtf.file import FileField
from wtforms import TextField, TextAreaField, RadioField
from wtforms.fields.html5 import DateField, EmailField, URLField
from wtforms.validators import email, length, optional, required, url

from ..frontend import DIVISIONS

class TeamForm(Form):
    ''' Form to submit a team
    '''
    name = TextField('Team Name', validators=[required()])
    slug = TextField('Slug', validators=[optional()])
    logo = FileField('Team Logo', validators=[optional()])
    picture = FileField('Team Picture', validators=[optional()])
    email = EmailField('Contact Email',
        validators=[required(), email()])
    roster_url = URLField('Roster Google Doc URL',
        validators=[url(), optional()])
    #division = RadioField('Division',
    #        choices=DIVISIONS, default=DIVISIONS[0][0])
    twitter = TextField('Twitter Handle', validators=[optional()])
    fb_url = URLField('Facebook URL', validators=[url(), optional()])
    brief_about = TextAreaField('Brief Description',
        validators=[optional(), length(max=255)])
    description = TextAreaField('Detailed Description',
            validators=[optional()])

ulti/__init__.py
from app import create_app

ulti/admin/__init__.py
from .views import admin

ulti/admin/views.py
from flask import (abort, Blueprint, flash, g, redirect,
                    render_template, request, url_for)

from flask.ext.classy import FlaskView, route
from flask.ext.security import (current_user, login_required,
                                roles_required)
from werkzeug import secure_filename

from .forms import TeamForm
from ..frontend import Team
from ..utils import s3_upload, s3_signer

admin = Blueprint('admin', __name__, url_prefix='/admin')


class AdminView(FlaskView):
    '''
    '''
    route_base = '/'
    decorators = [login_required, roles_required('super_admin')]

    def index(self):
        ''' Our main index view '''
        return render_template('admin/index.html')

    @route('/new', endpoint='new_team', methods=['GET','POST'])
    def new_team(self):
        ''' Our main index view '''
        team = Team()
        form = TeamForm(obj=team)
        if form.validate_on_submit():
            form.populate_obj(team)
            team.logo = ''
            team.picture = ''
            if form.logo.data:
                upload = s3_upload(form.logo.data.filename, form.logo)
                team.logo = upload
                flash('Logo uploaded to %s', upload)
            if form.picture.data:
                upload = s3_upload(form.picture.data.filename, form.picture)
                team.picture = upload
                flash('Picture uploaded to %s', upload)
            team.save()
            flash('New team added')
            return redirect(url_for('frontend.team', slug=team.slug))
        return render_template('admin/new.html', form=form)


class TeamAdminView(FlaskView):
    '''
    '''
    route_base = '/'
    decorators = [login_required,
        roles_required('super_admin')]

    @route('/<slug>/', endpoint='team', methods=['GET', 'POST'])
    def team(self, slug):
        '''  '''
        if not current_user.has_role('super_admin'):
            # TODO: Check if current user is 'owner' of this team
            flash('You do not have permission to view this page')
            return redirect(url_for('frontend.index'))

        team = Team.objects(slug=slug).first_or_404()
        form = TeamForm(obj=team)
        if form.validate_on_submit():
            if form.logo.data:
                upload_logo = s3_upload(form.logo)
            else:
                upload_logo = team.logo
            if form.picture.data:
                upload_picture = s3_upload(form.picture)
            else:
                upload_picture = team.picture
            form.populate_obj(team)
            team.logo = upload_logo
            team.picture = upload_picture
            print 'Updated team information %s' % team.to_dict()
            team.save()
            flash('Changes Saved')
            return render_template('admin/team.html',
                    team=team, form=form)
        return render_template('admin/team.html', team=team, form=form)

@login_required
@admin.route('/sign_s3/', endpoint='signS3')
def sign_s3():
    return s3_signer(request)

#Register our View Class
AdminView.register(admin)
TeamAdminView.register(admin)

ulti/app.py
import os

from flask import Flask, render_template
from flask.ext.security import MongoEngineUserDatastore

from .admin import admin
from .frontend import frontend
from .user import user, User, Role
from .utils import prettydate

from .config import Config, DevelopmentConfig, ProductionConfig
from .extensions import assets, db, mail, md, security, s3

# For import *
__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    admin,
    frontend,
    user,
)

def create_app(config=None, app_name=None, blueprints=None):
    '''Create a Flask app.'''

    if app_name is None:
        app_name = Config.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name, instance_relative_config=True)
    configure_app(app, config)
    configure_hook(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_template_filters(app)
    configure_error_handlers(app)

    return app

def configure_app(app, config=None):
    '''Different ways of configurations.'''

    # http://flask.pocoo.org/docs/api/#configuration
    if config:
        app.config.from_object(config)
    else:
        try:
            from local import LocalConfig
            app.config.from_object(LocalConfig)
        except:
            app.config.from_object(DevelopmentConfig)

def configure_extensions(app):
    # flask-mongoengine
    db.init_app(app)

    # flask-mail
    mail.init_app(app)

    # Setup Flask-Security
    user_datastore = MongoEngineUserDatastore(db, User, Role)
    security.init_app(app, user_datastore)

    # Flask assets
    assets.init_app(app)

    # markdown
    md.init_app(app)

    # flask s3
    s3.init_app(app)


def configure_blueprints(app, blueprints):
    '''Configure blueprints in views.'''

    for blueprint in blueprints:
        app.register_blueprint(blueprint)

def configure_template_filters(app):

    @app.template_filter()
    def time_ago(value):
        return prettydate(value)

def configure_logging(app):
    '''Configure file(info) and email(error) logging.'''

    if app.debug or app.testing:
        #skip loggin
        return

def configure_hook(app):

    @app.before_request
    def before_request():
        pass

def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template('errors/403.html'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html'), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template('errors/500.html'), 500

ulti/frontend/__init__.py
from .constants import *
from .models import Team
from .views import frontend

ulti/frontend/views.py
from flask import (abort, Blueprint, flash, g, redirect,
                    render_template, request, url_for)

from flask.ext.classy import FlaskView, route

from .models import Team

frontend = Blueprint('frontend', __name__, url_prefix='')

class TeamView(FlaskView):
    ''' Our base View for the main Item
    '''
    route_base = '/'

    @route('/', endpoint='index')
    def index(self):
        ''' Our main index view '''
        teams = Team.objects().order_by('-slug')
        return render_template('frontend/index.html', teams=teams)

    @route('/<slug>/', endpoint='team')
    def get(self, slug):
        ''' View for a single team
            TODO: Change this to subdomains
        '''
        team = Team.objects(slug=slug).first_or_404()
        return render_template('frontend/team.html', team=team)


#Register our View Class
TeamView.register(frontend)

ulti/user/__init__.py
from .models import User, Role
from .views import user

ulti/user/views.py
from flask import (Blueprint, abort)

from flask.ext.security import login_required

from .models import User


user = Blueprint('user', __name__, url_prefix='/user')


@login_required
@user.route('/')
def index():
    return abort(404)

ulti/templates/_base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="ClearType" content="true">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- DNS prefetch -->
        <link rel="dns-prefetch" href="//ajax.googleapis.com">
        {%- if config.PRODUCTION %}
        <link rel="dns-prefetch" href="//s3.amazonaws.com">
        {%- endif %}

        <title>{% block title %}PDX Ultimate{% endblock title %}</title>
        <meta name="description" content="{% block description %}{% endblock description %}">

        <!-- Styles -->
        {% block css -%}{%- endblock %}

        <!-- WebFonts -->
        <script src="//ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
        <script>
          WebFont.load({
            google: {
              families:  [ 'EB+Garamond::latin', 'Open+Sans:400italic,400,700,300:latin' ]
            }
          });
        </script>
    </head>
    <body class="{% block bodyclass %}{% endblock %}">
        <div role="document" class="document">
        {%- block siteheader -%}
        {% endblock siteheader -%}

        {%- block main %}
            <main role="main" class="main">
                <div class="page-header">
                {%- block pageheader -%}
                {% endblock pageheader -%}
                </div> <!-- .page-header  -->
                <div class="page-content">
                {%- with messages = get_flashed_messages() -%}
                      {% if messages %}
                        <ul class="flashes well">
                        {% for message in messages %}
                            <li>{{ message | safe}}</li>
                        {% endfor %}
                        </ul>
                      {% endif %}
                {%- endwith -%}
                {%- block content -%}
                {%- endblock content %}
                </div> <!-- .page-content  -->
                <div class="page-footer">
                {%- block pagefooter -%}
                {% endblock pagefooter -%}
                </div> <!-- .page-footer -->
            </main> <!-- main  -->
            {%- block sitefooter %}
            <footer role="contentinfo" class="footer">
                <div class="bottom cf">
                    <div class="wrapper">
                        <span class="copyright medium-float-left">
                            <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Copyright © 2014</a>
                            &nbsp;·&nbsp; PDX Ultimate{% if team and team.name %} / {{team.name}}{% endif %}
                        </span>
                        <span class="made medium-float-right">
                            {% if not team %}
                            <a href="#">Contact</a>
                            {% else %}
                            <a class="team-admin-link" href="{{url_for('admin.team', slug=team.slug)}}">Admin</a>
                            {% endif %}
                            &nbsp;·&nbsp;
                            <a href="http://joeahand.com">Made by <span class="useicons">&#xe635;</span></a>
                        </span>
                    </div>
                </div>
            </footer>
            {% endblock sitefooter -%}
        {%- endblock main %}
        </div> <!-- document -->
    {%- block footer_js -%}
    {%- endblock footer_js %}
    </body>
</html>